In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [22]:
print(os.getcwd()) # Get Current Working Directory ดูว่าเราอยู่ที่ไหนในระบบไฟล์

d:\Phee\Python project\streamlit-Dashboard\eda

In [23]:
df = pd.read_csv("../assets/vgsales.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [24]:
df_2 = df.sample(n = 100,random_state=4) #สุ่มแถวมา 5 แถว , ถ้าไม่มั random state จะสุ่มไปเรื่อยๆใช้อันนี้เพื่อเลือก state ที่แน่นอน 
df_2.reset_index(drop = True ,inplace = True) # reset index , inplace คือการเปลี่ยนแปลงข้อมูลเดิมโดยไม่ต้องเอาตัวแปรใหม่มารับ , drop คือ drop index เดิมทิ้ง 
df_2.drop('Rank', axis = 1 , inplace =True , errors = 'ignore') # ลบคอลัม Rank แทนที่ df_2 ที่เดิม และ ไม่สน error เพราะตอนรันที่หลังจะติด error rank ไม่มีอยู่จริงเพราะลบไปแล้ว
#df_test = df_2.reset_index(drop = True) #แบบนี้คือต้องเอาตัวแปรใหม่มารับ
df_2

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Leisure Suit Larry: Box Office Bust,PS3,2009.0,Adventure,Codemasters,0.06,0.03,0.00,0.01,0.10
1,High School Musical 2: Work This Out!,DS,2008.0,Misc,Disney Interactive Studios,0.50,0.52,0.00,0.13,1.15
2,Atelier Ayesha: The Alchemist of Dusk,PS3,2012.0,Role-Playing,Tecmo Koei,0.06,0.04,0.14,0.02,0.27
3,The Sims 2: Pets,PC,2006.0,Simulation,Electronic Arts,0.01,0.02,0.00,0.01,0.04
4,Super Street Fighter II,GEN,1993.0,Fighting,Capcom,0.00,0.00,0.15,0.00,0.15
...,...,...,...,...,...,...,...,...,...,...
95,Major League Baseball 2K12,PSP,2012.0,Sports,Take-Two Interactive,0.08,0.00,0.00,0.01,0.09
96,Dodge Racing: Charger vs Challenger,Wii,2009.0,Racing,Zushi Games,0.11,0.00,0.00,0.01,0.12
97,Remington Super Slam Hunting: Africa,Wii,2010.0,Sports,Mastiff,0.27,0.00,0.00,0.02,0.28
98,Viva Pinata: Pocket Paradise,DS,2008.0,Simulation,THQ,0.27,0.23,0.00,0.06,0.56
99,Sniper Elite 3,PS4,2014.0,Shooter,505 Games,0.22,0.33,0.00,0.13,0.68

In [25]:
df_3 = df_2.copy()
df_3[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']] = df_3[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].astype(str) + ' M'
df_3

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Leisure Suit Larry: Box Office Bust,PS3,2009.0,Adventure,Codemasters,0.06 M,0.03 M,0.0 M,0.01 M,0.1 M
1,High School Musical 2: Work This Out!,DS,2008.0,Misc,Disney Interactive Studios,0.5 M,0.52 M,0.0 M,0.13 M,1.15 M
2,Atelier Ayesha: The Alchemist of Dusk,PS3,2012.0,Role-Playing,Tecmo Koei,0.06 M,0.04 M,0.14 M,0.02 M,0.27 M
3,The Sims 2: Pets,PC,2006.0,Simulation,Electronic Arts,0.01 M,0.02 M,0.0 M,0.01 M,0.04 M
4,Super Street Fighter II,GEN,1993.0,Fighting,Capcom,0.0 M,0.0 M,0.15 M,0.0 M,0.15 M
...,...,...,...,...,...,...,...,...,...,...
95,Major League Baseball 2K12,PSP,2012.0,Sports,Take-Two Interactive,0.08 M,0.0 M,0.0 M,0.01 M,0.09 M
96,Dodge Racing: Charger vs Challenger,Wii,2009.0,Racing,Zushi Games,0.11 M,0.0 M,0.0 M,0.01 M,0.12 M
97,Remington Super Slam Hunting: Africa,Wii,2010.0,Sports,Mastiff,0.27 M,0.0 M,0.0 M,0.02 M,0.28 M
98,Viva Pinata: Pocket Paradise,DS,2008.0,Simulation,THQ,0.27 M,0.23 M,0.0 M,0.06 M,0.56 M
99,Sniper Elite 3,PS4,2014.0,Shooter,505 Games,0.22 M,0.33 M,0.0 M,0.13 M,0.68 M

In [43]:
df_GS = df_2.groupby(by=['Genre'])[['Global_Sales']].sum().round(1).reset_index()
df_GS

           Genre  Global_Sales
0         Action           7.3
1      Adventure           1.4
2       Fighting           1.5
3           Misc           1.8
4       Platform           1.0
5         Puzzle          12.4
6         Racing           1.6
7   Role-Playing           4.5
8        Shooter           8.8
9     Simulation           6.3
10        Sports           5.1
11      Strategy           1.0